version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      # - yarn install
      - npm run build

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
