version: 0.2

phases:
  install:
    commands:
      - yarn install
      - pip install --upgrade awscli
  pre_build:
    commands:
      - yarn install --production=true
  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  name: build-artifact-$(date +%Y-%m-%d)
