 -- SAFE BEGIN FOR CONCAT
INSERT INTO "Merit" ("order", "active", "value", "categorie", "name", "comment", "delay")
VALUES

(1, true, 10, 'Enchantements (actuels)', 'Casque', 'libram ou ZG', null),
(2, true, 15, 'Enchantements (actuels)', 'Epaulettes', 'exalté ZG ou +5 all resist', null),
(3, true, 05, 'Enchantements (actuels)', 'Cape', '', null),
(4, true, 10, 'Enchantements (actuels)', 'Plastron', '', null),
(5, true, 10, 'Enchantements (actuels)', 'Bracelet', '', null),
(6, true, 10, 'Enchantements (actuels)', 'Gants', '', null),
(7, true, 10, 'Enchantements (actuels)', 'Pantalon', 'libram ou ZG', null),
(8, true, 10, 'Enchantements (actuels)', 'Bottes', '', null),

(9, true, 10, 'Enchantements (actuels)', 'Arme droite', '', null),
(10, true, 10, 'Enchantements (actuels)', 'Arme gauche', 'automatique pour les armes 2 mains', null),
(11, true, 05, 'Enchantements (actuels)', 'Arme distance', '', null),

(1, true, 10, 'Equipement Pré-raid', 'Casque', '', null),
(2, true, 10, 'Equipement Pré-raid', 'Collier', '', null),
(3, true, 10, 'Equipement Pré-raid', 'Epaulettes', '', null),
(4, true, 10, 'Equipement Pré-raid', 'Cape', '', null),
(5, true, 10, 'Equipement Pré-raid', 'Plastron', '', null),
(6, true, 10, 'Equipement Pré-raid', 'Bracelet', '', null),
(7, true, 10, 'Equipement Pré-raid', 'Gants', '', null),
(8, true, 10, 'Equipement Pré-raid', 'Ceinture', '', null),
(9, true, 10, 'Equipement Pré-raid', 'Pantalon', '', null),
(10, true, 10, 'Equipement Pré-raid', 'Bottes', '', null),
(11, true, 10, 'Equipement Pré-raid', 'Anneau 1', '', null),
(12, true, 10, 'Equipement Pré-raid', 'Anneau 2', '', null),
(13, true, 10, 'Equipement Pré-raid', 'Bijou 1', '', null),
(14, true, 10, 'Equipement Pré-raid', 'Bijou 2', '', null),

(15, true, 10, 'Equipement Pré-raid', 'Arme droite', '', null),
(16, true, 10, 'Equipement Pré-raid', 'Arme gauche', 'automatique pour les armes 2 mains', null),
(17, true, 10, 'Equipement Pré-raid', 'Arme distance / relique / totem', '', null),

(1, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Casque', '', null),
(2, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Collier', '', null),
(3, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Epaulettes', '', null),
(4, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Cape', '', null),
(5, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Plastron', '', null),
(6, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Bracelet', '', null),
(7, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Gants', '', null),
(8, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Ceinture', '', null),
(9, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Pantalon', '', null),
(10, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Bottes', '', null),
(11, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Anneau 1', '', null),
(12, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Anneau 2', '', null),
(13, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Bijou 1', '', null),
(14, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Bijou 2', '', null),

(15, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Arme droite', '', null),
(16, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Arme gauche', 'automatique pour les armes 2 mains', null),
(17, true, 05, 'Equipement palier 1 (T1 / MC / R10)', 'Arme distance / relique / totem', '', null),

(1, true, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Casque', '', null),
(2, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Collier', '', null),
(3, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Epaulettes', '', null),
(4, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Cape', '', null),
(5, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Plastron', '', null),
(6, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Bracelet', '', null),
(7, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Gants', '', null),
(8, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Ceinture', '', null),
(9, true, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Pantalon', '', null),
(10, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Bottes', '', null),
(11, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Anneau 1', '', null),
(12, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Anneau 2', '', null),
(13, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Bijou 1', '', null),
(14, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Bijou 2', '', null),

(15, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Arme droite', '', null),
(16, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Arme gauche', 'automatique pour les armes 2 mains', null),
(17, false, 05, 'Equipement palier 2 (T2 / MC BiS / BWL / R13)', 'Arme distance / relique / totem', '', null),

(1, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Casque', '', null),
(2, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Collier', '', null),
(3, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Epaulettes', '', null),
(4, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Cape', '', null),
(5, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Plastron', '', null),
(6, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Bracelet', '', null),
(7, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Gants', '', null),
(8, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Ceinture', '', null),
(9, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Pantalon', '', null),
(10, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Bottes', '', null),
(11, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Anneau 1', '', null),
(12, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Anneau 2', '', null),
(13, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Bijou 1', '', null),
(14, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Bijou 2', '', null),

(15, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Arme droite', '', null),
(16, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Arme gauche', 'automatique pour les armes 2 mains', null),
(17, false, 05, 'Equipement palier 3 (T3 / Naxx / R14)', 'Arme distance / relique / totem', '', null),

(1, true, 10, 'Spécialisation', 'Publiée sur cet outil et à jour', 'https://fr.classic.wowhead.com/talent-calc', null),
(2, true, 15, 'Spécialisation', 'Validée par le Maître de classe', 'Pas une spé PvP', null),
(3, true, 10, 'Spécialisation', '100% PvE', 'Tous les points les plus opti au raid', null),
(4, true, 10, 'Spécialisation', 'Soigneur: Spécialisation non hybride', 'Pour tous les healers qui ne jouent pas tank ou DPS', null),

(1, true, 05, 'Grade', 'Avoir le grade Membre', 'également pour les Raideur', null),
(2, true, 05, 'Grade', 'Avoir le grade Raideur', 'également pour les Vétérans', null),
(3, true, 05, 'Grade', 'Avoir le grade Vétéran', 'également pour les Maîtres de classe', null),
(4, true, 05, 'Grade', 'Avoir le grade Maître de classe', 'également pour les Officiers', null),
(5, true, 05, 'Grade', 'Avoir le grade Officier', 'également pour le GM', null),
(6, true, 05, 'Grade', 'Avoir le grade GM', '', null),

(1, true, 05, 'Communauté', 'Présenté sur les forums', '', null),
(2, true, 05, 'Communauté', 'Photo dans le trombinoscope', '', null),
(3, true, 02, 'Communauté', 'Avoir un chat et avoir posté sa photo', 'dans le chabinoscope', null),
(4, true, 15, 'Communauté', 'Signer la charte de guilde', '', null),
(5, true, 15, 'Communauté', 'Porter le tabard de guilde', '', null),
(6, true, 03, 'Communauté', 'Avoir un avatar sur le forum', '', null),
(7, true, 03, 'Communauté', 'Avoir exactement le même pseudo sur le forum qu‘en jeu', '', null),
(8, true, 03, 'Communauté', 'Avoir un avatar sur le Discord', '', null),
(9, true, 03, 'Communauté', 'Avoir exactement le même pseudo sur le Discord qu‘en jeu', '', null),
(10, true, 02, 'Communauté', 'Avoir un micro correctement configuré sur Discord', '', null),

(1, true, 05, 'Communauté - forum', 'A fait un guide sur le forum', '', null),
(2, true, 05, 'Communauté - forum', 'A fait un guide vidéo sur le forum', '', null),
(3, true, 05, 'Communauté - forum', 'A partagé un screen de son interface sur le forum', '', null),
(4, true, 05, 'Communauté - forum', 'A partagé sa liste d‘addons / weakaura sur le forum', '', null),

(5, true, 05, 'Communauté - forum', '50 messages sur le forum', '', null),
(6, true, 05, 'Communauté - forum', '200 messages sur le forum', '', null),
(7, true, 05, 'Communauté - forum', '500 messages sur le forum', '', null),
(8, true, 05, 'Communauté - forum', '1000 messages sur le forum', '', null),

(1, true, 05, 'Ancienneté', 'Est un ancien Awaken (Nostalrius)', '', null),
(2, true, 05, 'Ancienneté', 'A rejoint Awaken avant le 27 août (Classic)', '', null),
(3, true, 05, 'Ancienneté', 'A rejoint Awaken il y a plus de 3 mois', '', null),
(4, true, 05, 'Ancienneté', 'A rejoint Awaken il y a plus de 6 mois', '', null),
(5, true, 05, 'Ancienneté', 'A rejoint Awaken il y a plus d‘un an', '', null),

(1, true, 07, 'Farm Guilde', 'A fourni un lotus noir à la guilde', 'dure 60 jours', 60),
(2, true, 07, 'Farm Guilde', 'A fourni plusieurs lotus noir à la guilde', 'Egalement pour le mérite précédent, dure 60 jours', 60),
(3, true, 07, 'Farm Guilde', 'Est un artisant de la guilde', 'Dépeuceur 315 / TDC craft Rési / Couture craft Rési / Forge craft Rési / Enchantement ++', null),

(1, true, 03, 'Accès Raid', 'Accès Onyxia', '', null),
(2, true, 03, 'Accès Raid', 'Accès Molten Core', '', null),
(3, true, 03, 'Accès Raid', 'Accès BWL', '', null),
(4, false, 03, 'Accès Raid', 'Accès Naxxramas', '', null),
(5, true, 05, 'Accès Raid', 'Accès à la Quintessence aquatique', '', null),
(6, true, 05, 'Accès Raid', 'Toujours une Quintessence aquatique dans le sac', '', null),

(1, true, 05, 'Raid', 'Possède les addons de raid obligatoires', '', null),

(2, true, 05, 'Raid', 'Toujours sous consommables', 'Boss + Trash', null),
(3, true, 05, 'Raid', 'Sous consommables quand nécessaire', 'A ajouter si "Toujours sous consommables"', null),
(4, true, 03, 'Raid', 'La bouffe, c‘est déjà pas mal', '', null),
(5, true, 03, 'Raid', '300 en bandages', '', null),

(6, true, 03, 'Raid', 'Toujours des popos dans le sac', 'Mana et Vie', null),

(7, true, 10, 'Raid', 'Stuff +140 résistance feu unbuff', '', null),
(8, true, 10, 'Raid', 'Stuff +140 résistance nature unbuff', '', null),
(9, false, 10, 'Raid', 'Stuff +140 résistance givre unbuff', '', null),

(10, true, 10, 'Raid', 'Avoir un sac Onyxia', '', null),
(11, true, 5, 'Raid', 'Avoir deux sacs Onyxia', '', null),
(12, true, 5, 'Raid', 'Avoir trois sacs Onyxia', '', null),
(13, true, 5, 'Raid', 'Avoir quatres sacs Onyxia', '', null),

(21, true, 10, 'Raid', 'Exalté Hydraxiens', '', null),
(22, true, 10, 'Raid', 'Exalté Gurubashi', '', null),
(23, true, 10, 'Raid', 'Exalté Cercle cénarien', '', null),
(24, true, 10, 'Raid', 'Exalté Progeniture de nozdormu', '', null),
(25, true, 10, 'Raid', 'Exalté Aube d‘argent', '', null),

(1, true, 5, 'PvE', 'J‘ai tué Ragnaros chez Awaken', '', null),
(2, true, 5, 'PvE', 'J‘ai tué Nefarian chez Awaken', '', null),
(3, true, 5, 'PvE', 'J‘ai tué C‘thun chez Awaken', '', null),
(4, true, 10, 'PvE', 'J‘ai tué Kel Thuzad chez Awaken', '', null),

(1, true, 10, 'Réputations de raids', 'Exalté Hydraxiens', '', null),
(2, true, 10, 'Réputations de raids', 'Exalté Gurubashi', '', null),
(3, true, 10, 'Réputations de raids', 'Exalté Cercle cénarien', '', null),
(4, true, 10, 'Réputations de raids', 'Exalté Progeniture de nozdormu', '', null),
(5, true, 10, 'Réputations de raids', 'Exalté Aube d‘argent', '', null),

(1, true, 10, 'PvP', 'Exalté Altérac (Equipement pré-raid épique)', '', null),
(2, true, 5, 'PvP', 'Grade PvP 6 : Garde de Pierre : Accès aux potions', '', null),
(3, true, 5, 'PvP', 'Grade PvP 10 : Equipement bleu', '', null),
(4, true, 5, 'PvP', 'Grade PvP 13 : Equipement épique', '', null),
(5, true, 10, 'PvP', 'Grade PvP 14 : Armes épiques', '', null),

(1, true, 05, 'Mérite', 'Atteindre 100 points de mérite validés', '', null),
(2, true, 05, 'Mérite', 'Atteindre 200 points de mérite validés', '', null),
(3, true, 05, 'Mérite', 'Atteindre 300 points de mérite validés', '', null),
(4, true, 05, 'Mérite', 'Atteindre 400 points de mérite validés', '', null),
(5, true, 05, 'Mérite', 'Atteindre 500 points de mérite validés', '', null),
(6, true, 05, 'Mérite', 'Atteindre 600 points de mérite validés', '', null),
(7, true, 05, 'Mérite', 'Atteindre 700 points de mérite validés', '', null),

(1, true, -80, 'Malus', 'J‘ai mal saisie un mérite et je me suis fait chopper', 'au cours du dernier mois', 30),
(2, true, -30, 'Malus', 'J‘ai manqué de respect envers un off ou un mdc', 'au cours du dernier mois', 30),
(3, true, -30, 'Malus', 'Je ne me suis pas inscrit en raid 2 fois', 'au cours du dernier mois', 30),
(4, true, -10, 'Malus', 'Je suis arrivé en retard en raid snas prévenir', 'au cours du dernier mois', 30),
(5, true, -50, 'Malus', 'J‘était inscrit au raid mais pas présent, sans prévenir', 'au cours des deux derniers mois', 60),
(6, true, -20, 'Malus', 'J‘ai pris la parole de manière inapropriée en raid', 'au cours du dernier mois', 30),
(7, true, -50, 'Malus', 'J‘ai menti sur ma spé ou respé sans le dire à mon MDC', 'au cours des deux derniers mois', 60),
(8, true, -10, 'Malus', 'Je suis venu en raid sans consommables', 'au cours du dernier mois', 30),
(9, true, -10, 'Malus', 'Je suis venu en raid sans enchantements', 'au cours du dernier mois', 30),
(10, true, -20, 'Malus', 'J‘ai pull un pack en mode kikoo', 'au cours du dernier mois', 30),
(11, true, -20, 'Malus', 'J‘ai fais wipe le raid sur une bombe', 'Vael/Gueedon au cours des deux derniers mois', 60),
(12, true, -20, 'Malus', 'J‘ai fais dépop les techniciens autour de Vael', 'au cours des deux derniers mois', 60),
(13, true, -20, 'Malus', 'J‘ai loot l‘or de raid à la place d‘un officier','au cours des deux derniers mois', 60);



-- TODO Futurs mérites de classes
-- INSERT INTO "Merit" ("order", "active", "value", "classId", "categorie", "name", "comment")
-- VALUES
-- (1, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Mage'),
-- 'Merite de Classe',
-- 'Avoir le pain et l‘eau rang max', ''),
-- (2, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Mage'),
-- 'Merite de Classe',
-- 'Avoir son pipot de bruyère', ''),
-- (3, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Prêtre'),
-- 'Merite de Classe',
-- 'Avoir sa bénédiction / Anathème enchantée', ''),
-- (4, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Prêtre'),
-- 'Merite de Classe',
-- 'Avoir sa suite de fauve', ''),
-- (5, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Druide'),
-- 'Merite de Classe',
-- 'Jouer au mouseover', ''),
-- (6, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Druide'),
-- 'Merite de Classe',
-- 'Avoir sa suite de fauve', ''),
-- (7, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Voleur'),
-- 'Merite de Classe',
-- 'Avoir un stuff 140+ RN unbuff', ''),
-- (8, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Voleur'),
-- 'Merite de Classe',
-- 'Avoir un stuff 140+ RF unbuff', ''),
-- (9, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Chasseur'),
-- 'Merite de Classe',
-- 'Avoir son arc épique', ''),
-- (10, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Chasseur'),
-- 'Merite de Classe',
-- 'Avoir un stuff 140+ RN unbuff', ''),
-- (11, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Chaman'),
-- 'Merite de Classe',
-- 'Jouer au mouseover', ''),
-- -- (12, false, 15,
-- -- (SELECT id FROM "Classes" WHERE "name"='Chaman'),
-- -- 'Merite de Classe',
-- -- 'Avoir sa Crépuscule', 'Chaman amélio uniquement'),
-- (13, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Guerrier DPS'),
-- 'Merite de Classe',
-- 'Avoir un stuff avec 390+ def', ''),
-- (14, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Guerrier Tank'),
-- 'Merite de Classe',
-- 'Avoir 230+ RF unbuff', ''),
-- (15, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Guerrier Tank'),
-- 'Merite de Classe',
-- 'Avoir un stuff avec 420+ def', '')
-- ;

-- INSERT INTO "Merit" ("order", "active",  "value", "classId", "categorie", "name", "comment")
-- VALUES
-- (1, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Démoniste'),
-- 'Merite de Classe - Epique',
-- 'Avoir 200+ résist ombre unbuff', ''),
-- (2, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Chasseur'),
-- 'Merite de Classe - Epique',
-- 'Solote Hache trippe', ''),
-- (3, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Chasseur'),
-- 'Merite de Classe - Epique',
-- 'Avoir son carquois épique', '')
-- ;

-- INSERT INTO "Merit" ("order", "active", "value", "classId", "categorie", "name", "comment")
-- VALUES
-- (1, false, 15,
-- (SELECT id FROM "Classes" WHERE "name"='Guerrier Tank'),
-- 'Merite de Classe - Légendaire',
-- 'Avoir sa Thunderfury', '')
-- ;